# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt', 'FreeBSD/Qt', 'Windows/Qt']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'

- 'on': ['Linux/Qt', 'FreeBSD/Qt']
  'require':
    'graphics/libksane': '@same'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
