#!/bin/bash

# OBSOLETE - port to SVN

RELEASE=kolourpaint_1_2_2_kde3_release

echo Tagging as release $RELEASE:

# templates
cvs tag $RELEASE kde-i18n/templates/docs/kdegraphics/kolourpaint.pot kde-i18n/templates/kdegraphics/kolourpaint.pot

num_tagged=0

# translations (except for docs)
for g in `cat kde-i18n/subdirs.pris | sed -e '/^xx$/d'`
do
    f=kde-i18n/$g
    g=$f/messages/kdegraphics/kolourpaint.po

    if [ -f $g ]
    then
        echo Language $f:
    
        cvs tag $RELEASE $g
    
        echo
        num_tagged=$((num_tagged + 1))
    fi
done

echo Tagged $num_tagged .po files
